# WARNING: this file is written by a script. To make changes,
# alter the config in lib/tasks/ci.rake and
# run `bundle exec rake dependabot`.
---
version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - default-Gemfile
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: gemfiles/rails-7.1.x
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - rails-7.1.x
  open-pull-requests-limit: 10
  allow:
  - dependency-name: rails
  ignore:
  - dependency-name: rails
    versions:
    - ">= 7.2"
- package-ecosystem: bundler
  directory: gemfiles/elasticsearch
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - elasticsearch
  open-pull-requests-limit: 10
  allow:
  - dependency-name: elasticsearch
- package-ecosystem: bundler
  directory: gemfiles/sidekiq-5.x
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - sidekiq-5.x
  open-pull-requests-limit: 10
  allow:
  - dependency-name: sidekiq
  ignore:
  - dependency-name: sidekiq
    versions:
    - ">= 6"
- package-ecosystem: bundler
  directory: gemfiles/sidekiq-7.x
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - sidekiq-7.x
  open-pull-requests-limit: 10
  allow:
  - dependency-name: sidekiq
  ignore:
  - dependency-name: sidekiq
    versions:
    - ">= 8"
- package-ecosystem: bundler
  directory: gemfiles/graphql-2.0.17
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - graphql-2.0.17
  open-pull-requests-limit: 10
  allow:
  - dependency-name: graphql
  ignore:
  - dependency-name: graphql
    versions:
    - ">= 2.0.18"
- package-ecosystem: bundler
  directory: gemfiles/rails-7.2.x
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - rails-7.2.x
  open-pull-requests-limit: 10
  allow:
  - dependency-name: rails
  ignore:
    dependency-name: rails
    versions:
    - ">= 7.3"
- package-ecosystem: bundler
  directory: gemfiles/rails-8.0.x
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - rails-8.0.x
  open-pull-requests-limit: 10
  allow:
  - dependency-name: rails
  ignore:
    dependency-name: rails
    versions:
    - ">= 8.1"
- package-ecosystem: bundler
  directory: gemfiles/rails-edge
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - rails-edge
  open-pull-requests-limit: 10
  allow:
  - dependency-name: rails
- package-ecosystem: bundler
  directory: gemfiles/sinatra-2.x
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - sinatra-2.x
  open-pull-requests-limit: 10
  allow:
  - dependency-name: sinatra
- package-ecosystem: bundler
  directory: gemfiles/sinatra-edge
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - sinatra-edge
  open-pull-requests-limit: 10
  allow:
  - dependency-name: sinatra
- package-ecosystem: bundler
  directory: gemfiles/grape-1.x
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - grape-1.x
  open-pull-requests-limit: 10
  allow:
  - dependency-name: grape
- package-ecosystem: bundler
  directory: gemfiles/grape-2.x
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - grape-2.x
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: gemfiles/grape-edge
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - grape-edge
  open-pull-requests-limit: 10
  allow:
  - dependency-name: grape
- package-ecosystem: bundler
  directory: gemfiles/sequel-4
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - sequel-4
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: gemfiles/sequel-5
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - sequel-5
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: gemfiles/ams-0.9.x
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - ams-0.9.x
  open-pull-requests-limit: 10
  allow:
  - dependency-name: active_model_serializers
  ignore:
  - dependency-name: active_model_serializers
    versions:
    - ">= 0.10"
- package-ecosystem: bundler
  directory: gemfiles/ams-0.10.x
  schedule:
    interval: weekly
    time: '13:00'
  labels:
  - dependencies
  - ams-0.10.x
  open-pull-requests-limit: 10
  allow:
  - dependency-name: active_model_serializers
