inherit_from:
  - .rubocop_todo.yml
  - .rubocop_cc.yml
inherit_gem:
  syntax_tree: config/rubocop.yml

# We want these to run on CodeClimate, but not in regular checks

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# we have too many gemfiles to move rspec-related deps out of the gemspec.
Gemspec/DevelopmentDependencies:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false
