ENV['MONGOID_VERSION'] = 'skip'
ENV['DELAYED_JOB_VERSION'] = 'none'
ENV['RAILS_EDGE'] = 'true'

eval_gemfile File.expand_path('../Gemfile.base', __dir__)
eval_gemfile File.expand_path('../Gemfile.rails-common', __dir__)

gem 'rails', git: 'https://github.com/rails/rails', branch: 'main'
