ENV["MONGOID_VERSION"] = "skip"
ENV["DELAYED_JOB_VERSION"] = "none"
ENV["RAILS_EDGE"] = "true"

eval_gemfile "../Gemfile.base"
eval_gemfile "../Gemfile.rails-common"

gem "rails", git: "https://github.com/rails/rails", branch: "main"
