source "https://rubygems.org"

gemspec path: "../.."

# TODO: Check if we need Rails
gem "rails", "~> 7.1.0"
gem "sqlite3", "~> 1.4"

gem "active_model_serializers", "~> 0.10.12"

gem "net-smtp", require: "false" if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new("3.1")
