source "https://rubygems.org"

gemspec path: "../.."

# TODO: Check if we need Rails
gem "rails", "~> 6.1.0"
gem "sqlite3"

gem "active_model_serializers", "~> 0.10.12"

if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new("3.1")
  gem "net-smtp", require: "false"
end
