source "https://rubygems.org"

gemspec path: "../.."

gem "haml"
gem "sinatra", "~> 3"
gem "sqlite3", "~> 1.4"

gem "sequel", "5.102.0" # There was an incompatibility with ruby 3 in versions 4.42 - 5.29.
