ENV["MOPED_VERSION"] = "skip"
ENV["MONGOID_VERSION"] = "skip"
ENV["TILT_VERSION"] = "~> 2.0"

eval_gemfile File.expand_path("../gemfiles/Gemfile.base", __dir__)

gem "rails", ">= 5.0.2"
gem "sinatra", "2.0.0.rc1"

gem "active_model_serializers"

group :development do
  gem "yard"
  gem "pry"
  gem "pry-byebug"
end

if ENV["CODECLIMATE_REPO_TOKEN"]
  gem "simplecov"
end

# Specify your gem's dependencies in skylight-core.gemspec
gemspec
