source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'pry'
gem 'pry-byebug'

if ENV['CODECLIMATE_REPO_TOKEN']
  gem "simplecov"
end

# Specify your gem's dependencies in skylight-core.gemspec
gemspec
