source "https://rubygems.org"

gemspec path: "../.."

# TODO: Check if we need Rails
gem "rails", "~> 6.1.0"
gem "sqlite3", "~> 1.4"

gem "elasticsearch"

gem "net-smtp", require: "false" if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new("3.1")
