source "http://rubygems.org"

# Hacks for unreleased versions
if ENV['RAILS_VERSION'] =~ /alpha/
  gem 'arel', github: 'rails/arel', branch: 'master'
  gem 'rails', github: 'rails/rails', branch: 'master'
else
  gem 'rails', ENV['RAILS_VERSION']
end

gem 'skylight', path: ENV['SKYLIGHT_GEM_PATH'] || "../../"