source "http://rubygems.org"

if ENV["RAILS_EDGE"]
  gem "rails", git: "https://github.com/rails/rails", branch: "main"
else
  gem "rails", ENV.fetch("RAILS_VERSION", nil)
end

gem "skylight", path: ENV.fetch("SKYLIGHT_GEM_PATH", "../../")
