source "https://rubygems.org"

gemspec path: "../.."

# TODO: Check if we need Rails
gem "rails", "~> 5.2.0"
gem "sqlite3"

# TODO: Should this be updated?
gem "active_model_serializers", git: "https://github.com/rails-api/active_model_serializers", branch: "0-10-stable"
