ENV['MONGOID_VERSION'] = 'skip'

eval_gemfile File.expand_path('../Gemfile.base', __dir__)

version = ENV['GRAPE_VERSION']
if version == 'edge'
  version = { git: 'https://github.com/ruby-grape/grape' }
end

gem 'grape', version
